### ISSUE TITLE
Sending BlackCoin from android wallet, can not brodcast transaction

### ISSUE THREAD

**Issue by ch3ll0v3k** [Coinomi/coinomi-android#143]
Hello!

When i try to send funds from android wallet to any other wallets, i get error, transaction broadcast;

And android adb logcat | get -i coinomi, show this when i try reproduce this error.

-------------------------------------------------------------------------------------------------------
I/StratumClient(14969): Unable to create socket for ServerAddress{host='sys-cce-1.coinomi.net', port=5049, path=''}
I/StratumClient(14969): Shutting down ServerAddress{host='sys-cce-1.coinomi.net', port=5049, path=''}
I/StratumClient(14969): Unable to create socket for ServerAddress{host='sys-cce-1.coinomi.net', port=5049, path=''}
I/StratumClient(14969): Shutting down ServerAddress{host='sys-cce-1.coinomi.net', port=5049, path=''}
I/StratumClient(14969): Shutting down ServerAddress{host='gulden-cce-2.coinomi.net', port=5040, path=''}
I/StratumClient(14969): Creating I/O streams to socket: Socket[address=gulden-cce-2.coinomi.net/176.9.65.41,port=5040,localPort=40621]
I/ServerClientBase(14969): Gulden client connected to ServerAddress{host='gulden-cce-2.coinomi.net', port=5040, path=''}
I/StratumClient(14969): Unable to create socket for ServerAddress{host='sys-cce-2.coinomi.net', port=5049, path=''}
I/StratumClient(14969): Shutting down ServerAddress{host='sys-cce-2.coinomi.net', port=5049, path=''}
I/ExchangeRatesProvider(14969): fetched exchange rates from https://ticker.coinomi.net/simple/to-crypto/USD, took 4 ms
E/ServerClient(14969): 	at com.coinomi.core.Preconditions.checkState(Preconditions.java:162)
E/ServerClient(14969): 	at com.coinomi.core.network.ServerClient.broadcastTxSync(ServerClient.java:510)
E/ServerClient(14969): 	at com.coinomi.core.network.ServerClient.broadcastTxSync(ServerClient.java:45)
E/ServerClient(14969): 	at com.coinomi.core.wallet.families.bitcoin.TransactionWatcherWallet.broadcastBitTxSync(TransactionWatcherWallet.java:1408)
E/ServerClient(14969): 	at com.coinomi.core.wallet.families.bitcoin.TransactionWatcherWallet.broadcastTxSync(TransactionWatcherWallet.java:1394)
E/ServerClient(14969): 	at com.coinomi.wallet.ui.MakeTransactionFragment$SignAndBroadcastTask.doInBackground(MakeTransactionFragment.java:775)
E/ServerClient(14969): 	at com.coinomi.wallet.ui.MakeTransactionFragment$SignAndBroadcastTask.doInBackground(MakeTransactionFragment.java:748)
E/ACRA    (14969): Not adding buildConfig to log. Class Not found : com.coinomi.wallet.BuildConfig. Please configure 'buildConfigClass' in your ACRA config
E/SendFragment(14969): com.coinomi.core.exceptions.TransactionBroadcastException: Error broadcasting transaction: af461d14682400705b5e1a82349e0b8582278c5e0ca1fcc7a9a351ffff3e0038
E/SendFragment(14969): 	at com.coinomi.wallet.ui.MakeTransactionFragment$SignAndBroadcastTask.doInBackground(MakeTransactionFragment.java:776)
E/SendFragment(14969): 	at com.coinomi.wallet.ui.MakeTransactionFragment$SignAndBroadcastTask.doInBackground(MakeTransactionFragment.java:748)
I/ACRA    (17519): Sending report /data/data/com.coinomi.wallet/app_ACRA-approved/2017-04-03T12:19:04.505+02:00-IS_SILENT.stacktrace
I/CoinService(14969): service start command: Intent { act=com.coinomi.wallet.service.cancel_coins_received cmp=com.coinomi.wallet/.service.CoinServiceImpl }
I/CoinService(14969): service start command: Intent { act=com.coinomi.wallet.service.connect_all_coin cmp=com.coinomi.wallet/.service.CoinServiceImpl }
I/StratumClient(14969): Unable to create socket for ServerAddress{host='sys-cce-1.coinomi.net', port=5049, path=''}
I/StratumClient(14969): Shutting down ServerAddress{host='sys-cce-1.coinomi.net', port=5049, path=''}
-------------------------------------------------------------------------------------------------------

I can receive fund. And block height is also correct. I hope this will fix this issue. 
And if you need i can put full stack trace from adb.

**Comment by ch3ll0v3k** [comment]
Here is more debug info:  The transaction is rejected, so the problem may be in the connection between servers ?? 


I/StratumClient(21679): Creating I/O streams to socket: Socket[address=gulden-cce-2.coinomi.net/176.9.65.41,port=5040,localPort=41189]
I/ServerClientBase(21679): Gulden client connected to ServerAddress{host='gulden-cce-2.coinomi.net', port=5040, path=''}
I/ServerClient(21679): Going to subscribe to block chain headers
I/ransactionWatcherWallet(21679): Got a Gulden block: 501082
D/STATUSBAR-NetworkController( 2824): refreshSignalCluster - setNWBoosterIndicators(false)
D/STATUSBAR-NetworkController( 2824): refreshSignalCluster: data=-1 bt=false
D/STATUSBAR-IconMerger( 2824): checkOverflow(336), More:false, Req:false Child:1
I/StratumClient(21679): Unable to create socket for ServerAddress{host='sys-cce-2.coinomi.net', port=5049, path=''}
I/StratumClient(21679): Shutting down ServerAddress{host='sys-cce-2.coinomi.net', port=5049, path=''}
I/StratumClient(21679): Shutdown message handler thread: pool-326-thread-1
I/StratumClient(21679): Finished listening for server replies
I/ServerClientBase(21679): Syscoin client stopped
I/ServerClientBase(21679): Reconnecting Syscoin in 16 seconds
D/STATUSBAR-NetworkController( 2824): onSignalStrengthsChanged signalStrength=SignalStrength: 99 99 -120 -160 -120 -1 -1 16 -115 2147483647 -12 -1 2147483647 gsm|lte 0x1000 level=1
I/ServerClient(21679): got tx TX rejected =?= f9d705d4d982694088c0674b11c7c0ec358695328af33ae707cbdd34216f93d6
E/ServerClient(21679): Could not get reply for blockchain.transaction.broadcast
E/ServerClient(21679): java.lang.IllegalStateException
E/ServerClient(21679): 	at com.coinomi.core.Preconditions.checkState(Preconditions.java:162)
E/ServerClient(21679): 	at com.coinomi.core.network.ServerClient.broadcastTxSync(ServerClient.java:510)
E/ServerClient(21679): 	at com.coinomi.core.network.ServerClient.broadcastTxSync(ServerClient.java:45)
E/ServerClient(21679): 	at com.coinomi.core.wallet.families.bitcoin.TransactionWatcherWallet.broadcastBitTxSync(TransactionWatcherWallet.java:1408)
E/ServerClient(21679): 	at com.coinomi.core.wallet.families.bitcoin.TransactionWatcherWallet.broadcastTxSync(TransactionWatcherWallet.java:1394)
E/ServerClient(21679): 	at com.coinomi.wallet.ui.MakeTransactionFragment$SignAndBroadcastTask.doInBackground(MakeTransactionFragment.java:775)
E/ServerClient(21679): 	at com.coinomi.wallet.ui.MakeTransactionFragment$SignAndBroadcastTask.doInBackground(MakeTransactionFragment.java:748)
E/ServerClient(21679): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/ServerClient(21679): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/ServerClient(21679): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/ServerClient(21679): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/ServerClient(21679): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/ServerClient(21679): 	at java.lang.Thread.run(Thread.java:841)
I/SpenGestureManager( 2446): setFocusWindow21020
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/PointerIcon( 2446): setMouseIconStyle1 pointerType: 1001iconType:101 flag:0
D/PointerIcon( 2446): setMouseCustomIcon IconType is same.101
E/ViewRootImpl(21679): sendUserActionEvent() mView == null
W/InputMethodManagerService( 2446): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@431b7010 attribute=null, token = android.os.BinderProxy@4392f878
D/CustomFrequencyManagerService( 2446): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1400000  uid : 1000  pid : 2446  pkgName : ACTIVITY_RESUME_BOOSTER@5
W/ActivityManager( 2446): mDVFSHelper.acquire()
D/PowerManagerService( 2446): setKeyboardVisibility: false
I/ransactionWatcherWallet(21679): Got a Blackcoin block: 1579025
I/dalvikvm(21679): Could not find method android.media.MediaCodecList.<init>, referenced from method org.acra.collector.MediaCodecListCollector.collectMediaCodecList
W/dalvikvm(21679): VFY: unable to resolve direct method 810: Landroid/media/MediaCodecList;.<init> (I)V
D/dalvikvm(21679): VFY: replacing opcode 0x70 at 0x0020
D/dalvikvm(21679): GC_CONCURRENT freed 3252K, 32% free 17850K/25876K, paused 4ms+8ms, total 105ms
E/ACRA    (21679): Not adding buildConfig to log. Class Not found : com.coinomi.wallet.BuildConfig. Please configure 'buildConfigClass' in your ACRA config
I/SurfaceFlinger( 1997): id=767 Removed TignTransac (10/12)
I/SurfaceFlinger( 1997): id=767 Removed TignTransac (-2/12)
E/SendFragment(21679): An unknown error occurred while sending coins
E/SendFragment(21679): com.coinomi.core.exceptions.TransactionBroadcastException: Error broadcasting transaction: f9d705d4d982694088c0674b11c7c0ec358695328af33ae707cbdd34216f93d6
E/SendFragment(21679): 	at com.coinomi.wallet.ui.MakeTransactionFragment$SignAndBroadcastTask.doInBackground(MakeTransactionFragment.java:776)
E/SendFragment(21679): 	at com.coinomi.wallet.ui.MakeTransactionFragment$SignAndBroadcastTask.doInBackground(MakeTransactionFragment.java:748)
E/SendFragment(21679): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/SendFragment(21679): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/SendFragment(21679): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/SendFragment(21679): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/SendFragment(21679): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/SendFragment(21679): 	at java.lang.Thread.run(Thread.java:841)
D/Toast   (21679):  checkMirrorLinkEnabled returns : false
D/Toast   (21679): showing allowed
D/PhoneStatusBar( 2824): setSemiTransparentMode=false, mTransparentMode=false, mSemiTransparentMode=false, mMultiWindowMode=false
D/StatusBarManagerService( 2446): semi p:21679,o:f
I/ExchangeRatesProvider(21679): fetched exchange rates from https://ticker.coinomi.net/simple/to-crypto/USD, took 10 ms
I/ExchangeRatesProvider(21679): fetched exchange rates from https://ticker.coinomi.net/simple/to-crypto/USD, took 20 ms
I/ExchangeRatesProvider(21679): fetched exchange rates from https://ticker.coinomi.net/simple/to-crypto/USD, took 18 ms
I/ExchangeRatesProvider(21679): fetched exchange rates from https://ticker.coinomi.net/simple/to-crypto/USD, took 20 ms
I/SELinux (24978): Function: selinux_android_load_priority , priority [2] , priority version is VE=SEPF_GT-I9305_4.4.4_0046
E/dalvikvm(24978): >>>>> Normal User
E/dalvikvm(24978): >>>>> com.coinomi.wallet:acra [ userId:0 | appId:10237 ]
I/SurfaceFlinger( 1997): id=768 createSurf (720x1280),1 flag=404, XalletActiv
I/SpenGestureManager( 2446): setFocusWindow21015
D/STATUSBAR-StatusBarManagerService( 2446): manageDisableList what=0x0 pkg=WindowManager.LayoutParams
D/PointerIcon( 2446): setMouseIconStyle1 pointerType: 1001iconType:101 flag:0
D/PointerIcon( 2446): setMouseCustomIcon IconType is same.101
D/Toast   (21679):  checkMirrorLinkEnabled returns : false
D/Toast   (21679): showing allowed
I/CoinService(21679): service start command: Intent { act=com.coinomi.wallet.service.cancel_coins_received cmp=com.coinomi.wallet/.service.CoinServiceImpl }
I/CoinService(21679): service start command: Intent { act=com.coinomi.wallet.service.connect_all_coin cmp=com.coinomi.wallet/.service.CoinServiceImpl }
I/ServerClientBase(21679): Forcing service startSyscoin
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
I/SurfaceFlinger( 1997): id=769 createSurf (1x1),1 flag=4, Uoast
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/PowerManagerService( 2446): [api] acquire WakeLock flags=0x2000000a tag=WindowManager uid=1000 pid=2446
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
I/BalanceFragment(21679): Got exchange rate: 0.08391811 USD
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
I/StratumClient(21679): Unable to create socket for ServerAddress{host='sys-cce-1.coinomi.net', port=5049, path=''}
I/StratumClient(21679): Shutting down ServerAddress{host='sys-cce-1.coinomi.net', port=5049, path=''}
I/StratumClient(21679): Finished listening for server replies
I/StratumClient(21679): Shutdown message handler thread: pool-330-thread-1
I/ServerClientBase(21679): Syscoin client stopped
I/ServerClientBase(21679): Reconnecting Syscoin in 16 seconds
I/ACRA    (24978): Sending report /data/data/com.coinomi.wallet/app_ACRA-approved/2017-04-03T13:36:57.182+02:00-IS_SILENT.stacktrace
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/BatteryService( 2446): level:89, scale:100, status:2, health:2, present:true, voltage: 4122, temperature: 320, technology: Li-ion, AC powered:false, USB powered:true, Wireless powered:false, icon:17303609, invalid charger:0, online:4, current avg:460, charge type:1, power sharing:false, high voltage charger:false
D/KeyguardUpdateMonitor( 2824): received broadcast android.intent.action.BATTERY_CHANGED
D/BatteryService( 2446): Sending ACTION_BATTERY_CHANGED.
D/KeyguardUpdateMonitor( 2824): handleBatteryUpdate
D/STATUSBAR-PhoneStatusBar( 2824):  mBrightnessEnablebySettings = true mBrightnessEnablebyBattery = true mBrightnessEnablebyDisableFlag = true mPmsBrightnessEnablebySettings = true
D/BatteryMeterView( 2824): ACTION_BATTERY_CHANGED : level:89 status:2 health:2
D/STATUSBAR-IconMerger( 2824): checkOverflow(336), More:false, Req:false Child:1
D/dalvikvm(24978): GC_CONCURRENT freed 1233K, 18% free 9150K/11028K, paused 3ms+2ms, total 23ms
D/CustomFrequencyManagerService( 2446): releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1400000  uid : 1000  pid : 2446  tag : ACTIVITY_RESUME_BOOSTER@5
W/ActivityManager( 2446): mDVFSHelper.release()
D/CustomFrequencyManagerService( 2446): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1400000  uid : 1000  pid : 2446  pkgName : ACTIVITY_RESUME_BOOSTER@9
I/SurfaceFlinger( 1997): id=763 Removed TignTransac (10/13)
I/SurfaceFlinger( 1997): id=763 Removed TignTransac (-2/13)
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/STATUSBAR-NetworkController( 2824): onSignalStrengthsChanged signalStrength=SignalStrength: 99 99 -120 -160 -120 -1 -1 16 -115 2147483647 -46 -1 2147483647 gsm|lte 0x1000 level=1
D/CustomFrequencyManagerService( 2446): releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1400000  uid : 1000  pid : 2446  tag : ACTIVITY_RESUME_BOOSTER@9
I/ACRA    (24978): Request received by server
D/STATUSBAR-NetworkController( 2824): onSignalStrengthsChanged signalStrength=SignalStrength: 99 99 -120 -160 -120 -1 -1 15 -115 2147483647 -10 -1 2147483647 gsm|lte 0x1000 level=1
V/AlarmManager( 2446): waitForAlarm result :8
D/KeyguardClockWidgetService(12895): onReceive action=android.intent.action.TIME_TICK
V/AlarmManager( 2446): ClockReceiver onReceive() ACTION_TIME_TICK
D/KeyguardUpdateMonitor( 2824): received broadcast android.intent.action.TIME_TICK
D/KeyguardUpdateMonitor( 2824): handleTimeUpdate
D/STATUSBAR-IconMerger( 2824): checkOverflow(336), More:false, Req:false Child:1
D/accuweather(20318): [MSC_Accu_Daemon]>>> U:983 [0:0] cDayONight() ::: sunrise is null 
D/accuweather(20318): [MSC_Accu_Daemon]>>> U:999 [0:0] cDayONight() ::: sunset is null 
D/accuweather(20318): [MSC_Accu_Daemon]>>> WCS:95 [0:0] checkDay:true, UtilgetIsDay():false
D/accuweather(20318): [MSC_Accu_Daemon]>>> WCS:97 [0:0] action:androidintentactionTIME_TICK
D/accuweather(20318): [MSC_Accu_Daemon]>>> AWDS:42 [0:0] Act
D/accuweather(20318): [MSC_Accu_Daemon]>>> AWDS:46 [0:0] Act : widgetappapaccuweatherdaemonactionCHANGE_ICON_OF_DAEMON, run:true
D/comsamsunglog(20318): [MSC_Accu_Daemon]>>> ====================================================================================================================
D/comsamsunglog(20318): [MSC_Accu_Daemon]>>> daemonappapaccuweather [Version : 14052301 ] [ 1 ] 
D/comsamsunglog(20318): [MSC_Accu_Daemon]>>> Header set to : ===> "accuweather" <===
D/comsamsunglog(20318): [MSC_Accu_Daemon]>>> ====================================================================================================================
D/accuweather(20318): [MSC_Accu_Daemon]>>> U:803 [0:0] IdlWdtchk !!!!
D/accuweather(20318): [MSC_Accu_Daemon]>>> U:795 [0:0] ACW not found!!
D/accuweather(20318): [MSC_Accu_Daemon]>>> U:808 [0:0] HERO pck Found!!!!
D/accuweather(20318): [MSC_Accu_Daemon]>>> AWDS:72 [0:0] SerStus:0,ASerStus:0,TmpS:1,AtRfr:3, UseCL0
D/accuweather(20318): [MSC_Accu_Daemon]>>> AWDS:426 [0:0] ====ACTION_SEC_CHANGE_ICON_OF_DAEMON===
D/accuweather(20318): [MSC_Accu_Daemon]>>> U:983 [0:0] cDayONight() ::: sunrise is null 
D/accuweather(20318): [MSC_Accu_Daemon]>>> U:999 [0:0] cDayONight() ::: sunset is null 
D/accuweather(20318): [MSC_Accu_Daemon]>>> AWDS:429 [0:0] checkDay:true, UtilgetIsDay():false
D/accuweather(20318): [MSC_Accu_Daemon]>>> AWDS:467 [0:0] data is not
I/BalanceFragment(21679): Got exchange rate: 0.08391811 USD
D/STATUSBAR-NetworkController( 2824): onSignalStrengthsChanged signalStrength=SignalStrength: 99 99 -120 -160 -120 -1 -1 15 -115 2147483647 -46 -1 2147483647 gsm|lte 0x1000 level=1
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/PowerManagerService( 2446): [api] [s] userActivity : event: 0 flags: 0 (uid: 1000 pid: 2446) eventTime = 6949604
D/PowerManagerService( 2446): [api] release WakeLock flags=0x2000000a tag=WindowManager uid=1000 pid=2446 (0x0)
D/PowerManagerService( 2446): [api] applyWakeLockFlagsOnReleaseLocked : userActivityNoUpdateLocked is called : SCREEN_BRIGHT_WAKE_LOCK        'WindowManager' ON_AFTER_RELEASE (uid=1000, pid=2446, ws=WorkSource{10237}) (elapsedTime=3305)
I/SurfaceFlinger( 1997): id=770 createSurf (1x1),1 flag=4, Uoast
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/PowerManagerService( 2446): [api] acquire WakeLock flags=0x2000000a tag=WindowManager uid=1000 pid=2446
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
I/SurfaceFlinger( 1997): id=769 Removed Uoast (12/13)
I/SurfaceFlinger( 1997): id=769 Removed Uoast (-2/13)
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 2824): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2824): handleKeyguardVisibilityChanged(1)
D/STATUSBAR-NetworkController( 2824): onSignalStrengthsChanged signalStrength=SignalStrength: 99 99 -120 -160 -120 -1 -1 15 -115 2147483647 -40 -1 2147483647 gsm|lte 0x1000 level=1
D/STATUSBAR-NetworkController( 2824): refreshSignalCluster - setNWBoosterIndicators(false)
D/STATUSBAR-NetworkController( 2824): refreshSignalCluster: data=-1 bt=false
D/STATUSBAR-IconMerger( 2824): checkOverflow(336), More:false, Req:false Child:1
I/ransactionWatcherWallet(21679): Got a Dogecoin block: 1658075
