### ISSUE TITLE
coinomi doesnt receive tx

### ISSUE THREAD

**Issue by justinvforvendetta** [Coinomi/coinomi-android#34]
ok so here is the debug output of the app:

07-09 10:47:06.442    1479-1556/com.coinomi.wallet.dev I/ransactionWatcherWallet﹕ Must get transactions for address DJEHEk6oKdCaEEqexyVN2WkB4Mcgfxpn6Q, status 194402f23639fa1ef45c20b61df98b37a9a792cadde0b78040db50e32f76d6ff
07-09 10:47:07.161    1479-1552/com.coinomi.wallet.dev I/ransactionWatcherWallet﹕ Going to fetch transaction with hash b737c2b447732ce3c67a37185bc58af6fd571b793ca1aa8a26924343d4daf5b8
07-09 10:47:07.621    1479-1552/com.coinomi.wallet.dev E/ServerClient﹕ Could not get reply for blockchain.transaction.get
    org.bitcoinj.core.ProtocolException: java.lang.ArrayIndexOutOfBoundsException: src.length=230 srcPos=184 dst.length=76 dstPos=0 length=76
            at org.bitcoinj.core.Message.readBytes(Message.java:471)
            at org.bitcoinj.core.TransactionInput.parse(TransactionInput.java:143)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:150)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:52)
            at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:126)
            at org.bitcoinj.core.Transaction.parse(Transaction.java:600)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:146)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:47)
            at org.bitcoinj.core.Transaction.<init>(Transaction.java:206)
            at com.coinomi.core.network.ServerClient$11.onSuccess(ServerClient.java:435)
            at com.coinomi.core.network.ServerClient$11.onSuccess(ServerClient.java:429)
            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
            at org.bitcoinj.utils.Threading$UserThread.run(Threading.java:106)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=230 srcPos=184 dst.length=76 dstPos=0 length=76
            at java.lang.System.arraycopy(Native Method)
            at org.bitcoinj.core.Message.readBytes(Message

and on the electrum server, we just get an error saying:

INFO:electrum-doged:TCP    xx.xx.xx.xxx:62862   41 unknown
INFO:electrum-doged:cache: invalidating DJEHEk6oKdCaEEqexyVN2WkB4Mcgfxpn6Q
postdata!!
[{"params": ["a37477b0732f39cb88ecbfddc1182e2b0f52b6843f903d05c3e27ff0915fa51f"], "method": "getrawtransaction", "id": 0}, {"params": ["4488bb75fc58f8b096832fe029a6db214b4293e49b70d233e067a22517dcf5c6"], "method": "getrawtransaction", "id": 1}, {"params": ["9e238cda431ac1d6bf31c7f8506bba0ef740e06ae83e730b5ce0f3d004aad0c5"], "method": "getrawtransaction", "id": 2}, {"params": ["39c6ec60c69a6d74d398547a89ea11886b87127b3dce638d7937aa37f17ab652"], "method": "getrawtransaction", "id": 3}, {"params": ["57baa5cacd16402856699d01451e18b99802895be975972172deb771e7a18907"], "method": "getrawtransaction", "id": 4}, {"params": ["b737c2b447732ce3c67a37185bc58af6fd571b793ca1aa8a26924343d4daf5b8"], "method": "getrawtransaction", "id": 5}]
INFO:electrum-doged:cache: invalidating DJEHEk6oKdCaEEqexyVN2WkB4Mcgfxpn6Q

here is the tx sent from coinomi to electrum server on the blockchain explorer:
http://darkchain.link/address/DJEHEk6oKdCaEEqexyVN2WkB4Mcgfxpn6Q

this was an example of the changes made to electrum client that helped it get/receive txs
https://github.com/doged/electrum-doged/commit/d319abc111c2ebc692c13ba7f3a021c1968bd75c#diff-0836bbd9465f2a87282f88740301e295

just adding a value of ntime.

kind of stuck here.

**Comment by justinvforvendetta** [comment]
the client is receiving communication/blocks from the electrum server, just not receiving the tx:
07-09 14:05:00.411    1533-1600/com.coinomi.wallet.dev I/ServerClient﹕ Server Dogecoindark version 0.9 OK
07-09 14:05:17.333    1533-1638/com.coinomi.wallet.dev I/ransactionWatcherWallet﹕ Got a Dogecoindark block: 193932

**Comment by justinvforvendetta** [comment]
more from the android logs in communication with the electrum server:

I/ransactionWatcherWallet﹕ Got a Dogecoindark block: 193937
07-09 14:07:37.950    1533-1638/com.coinomi.wallet.dev I/ransactionWatcherWallet﹕ Must get transactions for address DJEHEk6oKdCaEEqexyVN2WkB4Mcgfxpn6Q, status a5f4970742b92093f79be185aca70b4c2611aa9127da1f3475bb58c1c9c4b294
07-09 14:07:37.962    1533-1638/com.coinomi.wallet.dev I/ransactionWatcherWallet﹕ Status a5f4970742b92093f79be185aca70b4c2611aa9127da1f3475bb58c1c9c4b294 already updating
07-09 14:07:57.661    1533-1638/com.coinomi.wallet.dev I/ransactionWatcherWallet﹕ Got a Dogecoindark block: 193938
07-09 14:08:00.431    1533-1600/com.coinomi.wallet.dev I/ServerClient﹕ Server Dogecoindark version 0.9 OK
07-09 14:08:01.428    1533-1596/com.coinomi.wallet.dev I/ExchangeRatesProvider﹕ fetched exchange rates from https://ticker.coinomi.net/simple/to-crypto/USD (1288), {} chars, took {} ms

**Comment by justinvforvendetta** [comment]
so the coinomi does get the correct tx hash, as these two tx hashes are the only two tx's sent to the coinomi wallet, at least it is trying:
07-09 14:30:58.786    1533-1600/com.coinomi.wallet.dev I/ransactionWatcherWallet﹕ Going to fetch transaction with hash b737c2b447732ce3c67a37185bc58af6fd571b793ca1aa8a26924343d4daf5b8
07-09 14:30:58.802    1533-1600/com.coinomi.wallet.dev I/ransactionWatcherWallet﹕ Going to fetch transaction with hash 1a2f1da459771db2c792e9679aab3f07f626537067506cb16f684cb5974d0107
07-09 14:30:59.103    1533-1600/com.coinomi.wallet.dev E/ServerClient﹕ Could not get reply for blockchain.transaction.get
    org.bitcoinj.core.ProtocolException: java.lang.ArrayIndexOutOfBoundsException: src.length=230 srcPos=184 dst.length=76 dstPos=0 length=76
            at org.bitcoinj.core.Message.readBytes(Message.java:471)
            at org.bitcoinj.core.TransactionInput.parse(TransactionInput.java:143)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:150)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:52)
            at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:126)
            at org.bitcoinj.core.Transaction.parse(Transaction.java:600)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:146)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:47)
            at org.bitcoinj.core.Transaction.<init>(Transaction.java:206)
            at com.coinomi.core.network.ServerClient$11.onSuccess(ServerClient.java:435)
            at com.coinomi.core.network.ServerClient$11.onSuccess(ServerClient.java:429)
            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
            at org.bitcoinj.utils.Threading$UserThread.run(Threading.java:106)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=230 srcPos=184 dst.length=76 dstPos=0 length=76
            at java.lang.System.arraycopy(Native Method)
            at org.bitcoinj.core.Message.readBytes(Message.java:467)
            at org.bitcoinj.core.TransactionInput.parse(TransactionInput.java:143)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:150)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:52)
            at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:126)
            at org.bitcoinj.core.Transaction.parse(Transaction.java:600)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:146)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:47)
            at org.bitcoinj.core.Transaction.<init>(Transaction.java:206)
            at com.coinomi.core.network.ServerClient$11.onSuccess(ServerClient.java:435)
            at com.coinomi.core.network.ServerClient$11.onSuccess(ServerClient.java:429)
            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
            at org.bitcoinj.utils.Threading$UserThread.run(Threading.java:106)
07-09 14:30:59.549    1533-1600/com.coinomi.wallet.dev E/ServerClient﹕ Could not get reply for blockchain.transaction.get
    org.bitcoinj.core.ProtocolException: java.lang.ArrayIndexOutOfBoundsException: length=230; index=266
            at org.bitcoinj.core.Message.readVarInt(Message.java:457)
            at org.bitcoinj.core.TransactionInput.parseLite(TransactionInput.java:133)
            at org.bitcoinj.core.Message.<init>(Message.java:113)
            at org.bitcoinj.core.Message.<init>(Message.java:150)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:52)
            at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:126)
            at org.bitcoinj.core.Transaction.parse(Transaction.java:600)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:146)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:47)
            at org.bitcoinj.core.Transaction.<init>(Transaction.java:206)
            at com.coinomi.core.network.ServerClient$11.onSuccess(ServerClient.java:435)
            at com.coinomi.core.network.ServerClient$11.onSuccess(ServerClient.java:429)
            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
            at org.bitcoinj.utils.Threading$UserThread.run(Threading.java:106)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=230; index=266
            at org.bitcoinj.core.VarInt.<init>(VarInt.java:36)
            at org.bitcoinj.core.Message.readVarInt(Message.java:453)
            at org.bitcoinj.core.TransactionInput.parseLite(TransactionInput.java:133)
            at org.bitcoinj.core.Message.<init>(Message.java:113)
            at org.bitcoinj.core.Message.<init>(Message.java:150)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:52)
            at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:126)
            at org.bitcoinj.core.Transaction.parse(Transaction.java:600)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:146)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:47)
            at org.bitcoinj.core.Transaction.<init>(Transaction.java:206)
            at com.coinomi.core.network.ServerClient$11.onSuccess(ServerClient.java:435)
            at com.coinomi.core.network.ServerClient$11.onSuccess(ServerClient.java:429)
            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
            at org.bitcoinj.utils.Threading$UserThread.run(Threading.java:106)

**Comment by erasmospunk** [comment]
It seems that the transaction is being received but not correctly parsed.

Have you modified the custom [Bitcoinj Transaction](https://github.com/Coinomi/bitcoinj/blob/coinomi-0.12.2/core/src/main/java/org/bitcoinj/core/Transaction.java) (on branch coinomi-0.12.2)? Take a look at the PEERCOIN network family.

**Comment by justinvforvendetta** [comment]
ah i see, that looks like it will work, as it compensates for the extra tx. where in coinomi can i pull from a different repo for a modified bitcoinj that i add dogecoindark to the network family with blackcoin and the rest?

**Comment by erasmospunk** [comment]
You need to checkout `coinomi-0.12.2` branch from https://github.com/Coinomi/bitcoinj, fix Doged and make a pull request to the `coinomi-0.12.2` branch in the same repository.

**Comment by justinvforvendetta** [comment]
done! so once this is merged, coinomi will pull from 0.12.2, and not master?

**Comment by justinvforvendetta** [comment]
oh i see it in libs.. so i can create a jar from the repo i forked/made pull request from, in the mean time.

**Comment by justinvforvendetta** [comment]
ok i tried putting it in a family with peercoin etc, but came back with:

07-10 12:46:31.668    1395-1465/com.coinomi.wallet.dev I/ransactionWatcherWallet﹕ Must get transactions for address DJEHEk6oKdCaEEqexyVN2WkB4Mcgfxpn6Q, status bd3bb2036680a539dd8ca6b0ea5e753fe8249dc40009d8ca25799816b7a7bdb1
07-10 12:46:31.881    1395-1429/com.coinomi.wallet.dev I/ransactionWatcherWallet﹕ Going to fetch transaction with hash 77dc0104719895d74dd8f28f921df7a9674516d305ab139537ebe7c754bfd16a
07-10 12:46:32.111    1395-1429/com.coinomi.wallet.dev E/ServerClient﹕ Could not get reply for blockchain.transaction.get
    org.bitcoinj.core.ProtocolException: java.lang.ArrayIndexOutOfBoundsException: length=377; index=384
            at org.bitcoinj.core.Message.readVarInt(Message.java:457)
            at org.bitcoinj.core.TransactionInput.parseLite(TransactionInput.java:133)
            at org.bitcoinj.core.Message.<init>(Message.java:113)
            at org.bitcoinj.core.Message.<init>(Message.java:150)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:52)
            at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:126)
            at org.bitcoinj.core.Transaction.parse(Transaction.java:601)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:146)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:47)
            at org.bitcoinj.core.Transaction.<init>(Transaction.java:207)
            at com.coinomi.core.network.ServerClient$11.onSuccess(ServerClient.java:435)
            at com.coinomi.core.network.ServerClient$11.onSuccess(ServerClient.java:429)
            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
            at org.bitcoinj.utils.Threading$UserThread.run(Threading.java:106)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=377; index=384
            at org.bitcoinj.core.VarInt.<init>(VarInt.java:36)
            at org.bitcoinj.core.Message.readVarInt(Message.java:453)
            at org.bitcoinj.core.TransactionInput.parseLite(TransactionInput.java:133)
            at org.bitcoinj.core.Message.<init>(Message.java:113)
            at org.bitcoinj.core.Message.<init>(Message.java:150)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:52)
            at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:126)
            at org.bitcoinj.core.Transaction.parse(Transaction.java:601)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:146)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:47)
            at org.bitcoinj.core.Transaction.<init>(Transaction.java:207)
            at com.coinomi.core.network.ServerClient$11.onSuccess(ServerClient.java:435)
            at com.coinomi.core.network.ServerClient$11.onSuccess(ServerClient.java:429)
            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
            at org.bitcoinj.utils.Threading$UserThread.run(Threading.java:106)
07-10 12:47:00.158    1395-1434/com.coinomi.wallet.dev I/ExchangeRatesProvider﹕ fetched exchange rates from https://ticker.coinomi.net/simple/to-crypto/USD (35), {} chars, took {} ms
07-10 12:47:00.177    1395-1435/com.coinomi.wallet.dev I/ExchangeRatesProvider﹕ fetched exchange rates from https://ticker.coinomi.net/simple/to-crypto/USD (56), {} chars, took {} ms
07-10 12:47:00.209    1395-1426/com.coinomi.wallet.dev I/ExchangeRatesProvider﹕ fetched exchange rates from https://ticker.coinomi.net/simple/to-crypto/USD (110), {} chars, took {} ms
07-10 12:47:00.322    1395-1429/com.coinomi.wallet.dev I/ServerClient﹕ Server Dogecoindark version 0.9 OK

**Comment by justinvforvendetta** [comment]
on the electrum server side, it just says invalidating DJEHEk6oKdCaEEqexyVN2WkB4Mcgfxpn6Q

**Comment by justinvforvendetta** [comment]
think i should try creating a new wallet, instead of trying to restore the one i initially made?

**Comment by erasmospunk** [comment]
Try to pull the latest code where I improved the coin family mechanism. It is no longer required to modify the coinomi bitcoinj library. Just set in the CoinType the variable `family = PeerFamily.get();`.

**Comment by justinvforvendetta** [comment]
this is interesting, i didnt get this on any of my previous coinomi compiles.. 
C:\Users\sunerok\Documents\GitHub\testdroid\wallet\src\main\java\com\coinomi\wallet\ui\AboutActivity.java
Error:(28, 44) error: cannot find symbol variable translation_globe

**Comment by justinvforvendetta** [comment]
i removed that line, and it works now! decimal places are off by 2 though, but it worked!

**Comment by erasmospunk** [comment]
Try setting the `unitExponent` in the CoinType to 6 to fix the decimal places error.

**Comment by justinvforvendetta** [comment]
ill make a pull request later today <3
