### ISSUE TITLE
x11 pos/pow

### ISSUE THREAD

**Issue by justinvforvendetta** [Coinomi/coinomi-android#61]
i have a soon to be released coins electrum server up and running properly.. just had to add x11 and ntime to it.. and i did the reorg fix.. its solid and hasnt crashed now since i started it two days ago.. 

im trying to use the bitfamily, as per dash's config.. but im getting a strange error on the android studio debug: 

http://pastebin.com/K1MZ0a1q

**Comment by justinvforvendetta** [comment]
11-05 18:42:29.235    1392-1457/com.coinomi.wallet.dev E/ServerClient﹕ Could not get reply for blockchain.transaction.get
    org.bitcoinj.core.ProtocolException: java.lang.ArrayIndexOutOfBoundsException: src.length=229 srcPos=217 dst.length=92 dstPos=0 length=92
            at org.bitcoinj.core.Message.readBytes(Message.java:471)
            at org.bitcoinj.core.TransactionInput.parse(TransactionInput.java:143)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:150)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:52)
            at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:126)
            at org.bitcoinj.core.Transaction.parse(Transaction.java:602)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:146)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:47)
            at org.bitcoinj.core.Transaction.<init>(Transaction.java:203)
            at com.coinomi.core.network.ServerClient$10.onSuccess(ServerClient.java:444)
            at com.coinomi.core.network.ServerClient$10.onSuccess(ServerClient.java:438)
            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
            at org.bitcoinj.utils.Threading$UserThread.run(Threading.java:107)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=229 srcPos=217 dst.length=92 dstPos=0 length=92
            at java.lang.System.arraycopy(Native Method)
            at org.bitcoinj.core.Message.readBytes(Message.java:467)
            at org.bitcoinj.core.TransactionInput.parse(TransactionInput.java:143)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:150)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:52)
            at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:126)
            at org.bitcoinj.core.Transaction.parse(Transaction.java:602)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:146)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:47)
            at org.bitcoinj.core.Transaction.<init>(Transaction.java:203)
            at com.coinomi.core.network.ServerClient$10.onSuccess(ServerClient.java:444)
            at com.coinomi.core.network.ServerClient$10.onSuccess(ServerClient.java:438)
            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
            at org.bitcoinj.utils.Threading$UserThread.run(Threading.java:107)

**Comment by justinvforvendetta** [comment]
hm peerfamily worked. just had to take out the signed msg.
